[package]
name = "rash"
version = "0.1.0"
edition = "2024"

[dependencies]
libc = "0.2.170"
whoami = "1.5.2"
[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["consoleapi", "processenv", "wincon", "winnt", "winbase"] }
